### ISSUE TITLE
Remove Arbitrator court from Kleros-Interaction if need be

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#109]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitratorCourt.sol

I don't know why this contract is in Kleros-interaction, it looks like a component of Kleros.

**Comment by ferittuncer** [comment]
I agree. Moving to Kleros then.

**Comment by ferittuncer** [comment]
Made a change in Kleros. Now deleting from Kleros Interaction.
