### ISSUE TITLE
Flaky ArbitrableKitty test - shared custody - should return correct custody information

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros-interaction#121]
"Should return correct custody information" test sometimes fail even though there is no related change.

**Comment by mtsalenc** [comment]
Closing this as it was fixed in https://github.com/kleros/kleros-interaction/commit/29b8c651b84aa231685db0f920506c5107493d31

**Comment by mtsalenc** [comment]
It seems this is still present, causing tests to fail sometimes.

**Comment by heychessy** [comment]
I am bit confused here, is the bug still open or not? Can someone please explain the specific issue with the test?
