### ISSUE TITLE
Update ERC792 

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#125]
Arbitrator.sol has been changed since then

**Comment by epiqueras** [comment]
Changes for Arbitrator.sol:
- Return values `uint fees` => `uint fee`.
- `createDispute` now has `_choices`.
- `function appealPeriod(uint _disputeID) public view returns(uint start, uint end) {}`.
- Index `_arbitrable` in events.
- `event AppealPossible(uint indexed _disputeID, Arbitrable indexed _arbitrable);`.

**Comment by clesaege** [comment]
Done: https://github.com/ethereum/EIPs/issues/792
