### ISSUE TITLE
Decrease Cognitive Load on MultiPartyInsurableFees.sol

### ISSUE THREAD

**Issue by mtsalenc** [kleros/kleros-interaction#141]
The code should be refactored to be more readable.
Example:
The method `fundDispute()` calculates `_paidFees.totalContributedPerSide.length - 1` several times, to get the last index of the list, which makes it harder to digest the code.

**Comment by ferittuncer** [comment]
https://github.com/kleros/kleros-interaction/pull/129#discussion_r223015210

**Comment by epiqueras** [comment]
This is to avoid solidity max call stack size errors, but maybe we can find a middle ground.

**Comment by epiqueras** [comment]
We should try to break it into pure functions and remove the need for the cache.
