### ISSUE TITLE
Require arbitrator to be consistent with ruling during and after appeal periods

### ISSUE THREAD

**Issue by mtsalenc** [kleros/kleros-interaction#147]
On the scope of [line 99](https://github.com/kleros/kleros-interaction/blob/a0259a0c901e5c354e8c59b14fc0ae05eba0df29/contracts/standard/arbitration/AppealableArbitrator.sol#L99)

In the case that the appeal period passed and no one appealed, the function should `require(_ruling == disputes[_disputeID].ruling)`. Otherwise an arbitrator can rule in favor of `partyA`, then, after the appeal period passes, rule in favor of `partyB`.

**Comment by epiqueras** [comment]
Better to just rule with `disputes[_disputeID].ruling`.
