### ISSUE TITLE
Deal with fees paid in case the dispute is not funded

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#151]
Currently, if the dispute fails to receive sufficient fees, the fees paid are just kept by the contract.
https://github.com/kleros/kleros-interaction/blob/2b951c1b1722ac733cf2f5610167df73ec4794ba/contracts/standard/arbitration/composed-arbitrable/example/TwoPartyArbitrableEscrowPayment.sol#L131

We need to refund them or give them to the winner of the dispute whichever is easier so they are not lost.

**Comment by mtsalenc** [comment]
The fees can be withdrawn by participants by calling the `withdrawReward()`
