### ISSUE TITLE
Update agreement.ruling when inverting arbitrator`s ruling

### ISSUE THREAD

**Issue by mtsalenc** [kleros/kleros-interaction#154]
Ruling in favor of the looser when the winner fails to fund his side of an appeal means to simply invert the previous ruling. `agreement.ruling` which was set by the parent method `MultiPartyAgreements.executeRuling()` should be updated to reflect this.

https://github.com/kleros/kleros-interaction/blob/fb8a7eb3a304f764c4b91cc3d92535cf98b7fa08/contracts/standard/arbitration/composed-arbitrable/example/TwoPartyArbitrableEscrowPayment.sol#L126

**Comment by epiqueras** [comment]
It shouldn't, agreement.ruling should keep the original ruling, otherwise the history is lost.
