### ISSUE TITLE
Review CentralizedArbitrator contract

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros-interaction#157]

**Comment by mtsalenc** [comment]
In what branch is the latest code?

**Comment by ferittuncer** [comment]
Master.

**Comment by satello** [comment]
https://docs.google.com/document/d/1smKQOjifIhugQai9CrXyrgJnLo9vSY7kh4ndjojsXMw/edit?usp=sharing

**Comment by clesaege** [comment]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/CentralizedArbitrator.sol

**Comment by epiqueras** [comment]
@ferittuncer Can you make a new issue following: https://kleros.gitbook.io/contributing-md/smart-contract-workflow/reviews-and-bug-bounties#pre-review
