### ISSUE TITLE
Review BondingCurve.sol

### ISSUE THREAD

**Issue by yushih** [kleros/kleros-interaction#162]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/bonding-curve/BondingCurve.sol

**Comment by mtsalenc** [comment]
https://docs.google.com/document/d/1esp_f8mHfxb7V4ghkxoUipi8XrD2r58YMBQu1MSccmI/edit?usp=sharing

**Comment by yushih** [comment]
No need any more since we are going to use UniSwap.
