### ISSUE TITLE
Pre-Review CentralizedArbitrator

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros-interaction#169]
"RAB" version of #157.

**Comment by clesaege** [comment]
https://docs.google.com/document/d/1nfnxULpHlwGa2_ehahFcvbQdYh0gp88CRraXAhm57A8/edit#

That's just minor comments.

**Comment by ferittuncer** [comment]
- Updated authors.

- Left DisputeStruct unchanged because it can't be simply "Dispute" as there is a naming conflict with IArbitrable and this creates a compile error when a contract inherits from both contracts, like AppealableArbitrator. But we can find a better name of course.

- Fixes indentation errors in Doxygen blocks.

------

I also suggest that we anonymize unused parameters (in general, not only for this contract) as such:

Before:
```
/** @dev Cost of appeal. Since it is not possible, it's a high value which can never be paid.
 *  @param _disputeID ID of the dispute to be appealed. Not used by this contract.
 *  @param _extraData Not used by this contract.
 *  @return fee Amount to be paid.
 */
function appealCost(uint _disputeID, bytes _extraData) public view returns(uint fee) {
    return NOT_PAYABLE_VALUE;
}
```

After:
```
/** @dev Cost of appeal. Since it is not possible, it's a high value which can never be paid.
 *  @return fee Amount to be paid.
 */
function appealCost(uint, bytes) public view returns(uint fee) {
    return NOT_PAYABLE_VALUE;
}
```
