### ISSUE TITLE
Implement a centralized arbitrator court

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#17]
Make an Arbitrator contract where the decisions are made by the majority of court members.
The arbitration fees are to be split among all court members proportionally.
Appeals are not possible.

**Comment by tobyweed** [comment]
Is this issue still open, or is it addressed [here](https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/CentralizedArbitrator.sol)? A little confused, esp because this issue was posted a week after the centralized arbitrator contract was last edited

**Comment by clesaege** [comment]
Yes, you linked to a centralized arbitrator controlled by one unique address.
This issue is about a centralized court, where the vote is made at the majority of the members.
