### ISSUE TITLE
Review CentralizedArbitrator

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros-interaction#173]
"RAB" (new review flow) version of #157

**Comment by ferittuncer** [comment]
I suggest that we anonymize unused parameters (in general also, not only for this contract) as such:

Before:
```
/** @dev Cost of appeal. Since it is not possible, it's a high value which can never be paid.
 *  @param _disputeID ID of the dispute to be appealed. Not used by this contract.
 *  @param _extraData Not used by this contract.
 *  @return fee Amount to be paid.
 */
function appealCost(uint _disputeID, bytes _extraData) public view returns(uint fee) {
    return NOT_PAYABLE_VALUE;
}
```

After:
```
/** @dev Cost of appeal. Since it is not possible, it's a high value which can never be paid.
 *  @return fee Amount to be paid.
 */
function appealCost(uint, bytes) public view returns(uint fee) {
    return NOT_PAYABLE_VALUE;
}
```

The rationale behind is, a reader of auto-generated documentation can be misguided like as if those parameters are used for calculating the returned value. Also, anonymization lets us have a shorter source code.

**Comment by epiqueras** [comment]
I’d rather have it follow the ERC naming. Otherwise it might confuse
readers. The comments already explain they are unused.

**Comment by clesaege** [comment]
Yeah, we should lower the reviewing time, low code size is a mean to it, not the end goal.
But anonymizing the params, even if we reduce code size reviewers will need to look at what it does and this will increase the reviewing time.

**Comment by ferittuncer** [comment]
What is the benefit of using two giveRulings, one public one internal, instead of single external one? As far as I can see giveRuling is only called externally, right? @clesaege @epiqueras @satello

**Comment by epiqueras** [comment]
It's used by contracts that inherit it. E.g. AppealableArbitrator.sol.

**Comment by epiqueras** [comment]
https://github.com/kleros/kleros-interaction/blob/eaa0cac6de07269e5d4ad35769a2e1f320c14ffd/contracts/standard/arbitration/CentralizedArbitrator.sol#L95

**Comment by n1c01a5** [comment]
my review https://docs.google.com/document/d/1YPge47tgx_mfjX2aVjE0BSAwK7MBpkBU0gobZ6gH0Tc/edit#

**Comment by n1c01a5** [comment]
Bounty phase: see https://github.com/kleros/kleros-interaction/issues/189
