### ISSUE TITLE
Create a Versioning Proxy Contract

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-interaction#19]
That handles ENS records, authorized devs, upgrades, rollbacks etc. Spec in progress.

**Comment by clesaege** [comment]
Tentative specs:

The proxy contract is the an Arbitrator  contract the Arbitrable ones are linked to. It is linked to an Arbitrator one using ENS.
It transfers disputes to the Arbitrator one. But also keep track of them.
During a change of Arbitrator (in our case new version of Kleros), it must be able to recreate current disputes in the new Arbitrator.

**Comment by clesaege** [comment]
In the case it relies on ENS, it seems not to need any specific dev access as devs would use ENS update to update the Arbitrator. We could also make a simpler version not relying on ENS but where the owner could update the Arbitrator. Note that the owner can be a governance smart contract.

**Comment by epiqueras** [comment]
I thought we would still want to do the upgrade through the proxy and have
that update the ENS.

This way the proxy can keep a log of all versions and support rollbacks or
specific version targeting.

**Comment by clesaege** [comment]
So disputes would not get moved to the new Arbitrator contract. In this case we could allow disputes which started to resolve but in case of appeal, make a dispute to the new contract.

**Comment by epiqueras** [comment]
Yes exactly, only move disputes that are not closed.

**Comment by clesaege** [comment]
Yeah, but the problem is that if the court is updated, people may stop using the previous one, so it would not be secured, so in case of appeals, it should go to the new court.

**Comment by epiqueras** [comment]
Yes, that's what I meant, `appealed !== closed`.
