### ISSUE TITLE
Review MultipleArbitrableTokenTransaction.

### ISSUE THREAD

**Issue by n1c01a5** [kleros/kleros-interaction#200]
See https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol

**Comment by ferittuncer** [comment]
### No functional issues. :heavy_check_mark: 

https://github.com/kleros/kleros-interaction/blob/1a273d8e7df57244fb8405105d377b36480a7714/contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol#L344

A dust amount will be left but it's not significant I think. Looks OK.

**Comment by mtsalenc** [comment]
https://docs.google.com/document/d/1NSMFEjcpQbWIGobOZn0Vl1mkJZVg2DHM9ZGAff6j4q8/edit?usp=sharing

Please tell me when you are done and I'll add my name to the reviewers list.

**Comment by n1c01a5** [comment]
Done. I left some comments in your doc.

**Comment by unknownunknown1** [comment]
My review:
https://docs.google.com/document/d/1fYMxGQRVDAP8VvYGYcm6TTspLl-xeyW2_juJ6tx7-Ok/edit?usp=sharing
No serious issues

**Comment by n1c01a5** [comment]
@unknownunknown1 done

**Comment by n1c01a5** [comment]
From @clesaege, "we need one contract per token as a vulnerability mitigation".

**Comment by clesaege** [comment]
My review: https://docs.google.com/document/d/15rgNrGiBNsWMlrdXqfIka7jRJXztBiAyUv1yzP1qQ7Y/edit?usp=sharing
@n1c01a5

**Comment by unknownunknown1** [comment]
Did review on updated contract https://docs.google.com/document/d/1xeoBOenUJqjCc2eneRlUp_OaBE4ynRLQatHMR8JB1Mg/edit?usp=sharing

**Comment by n1c01a5** [comment]
@clesaege I think the refund of seller Fee is missed https://github.com/kleros/kleros-interaction/blob/38da0dd946dcfda8d0a7fc6e7f98737ba3c846f2/contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol#L340

**Comment by unknownunknown1** [comment]
https://docs.google.com/document/d/19GwyBfrmhGojR6BJoZD_0qbn8Hc-Ou9aGEnjPcBsvyk/edit?usp=sharing

**Comment by unknownunknown1** [comment]
Post my review here because Slack deletes it.

Couple of small issues in both contracts:
1. It's better to rephrase require text "The transaction can't be disputed" to "The transaction shouldn't be disputed". Would be more accurate
2. I'm not sure it's an issue but it's possible to submit evidence to resolved disputes. "require(transaction.status >= Status.DisputeCreated"
3. Comment to timeOutBySender function should start with "Reimburse sender" instead of "Pay sender", and comment to timeOutByReceiver should start with "Pay receiver", since we've made it so that receiver is the one providing services.

**Comment by clesaege** [comment]
It has been update, you can review again.

**Comment by mtsalenc** [comment]
I reviewed the latest version (commit 9706416) and found no significant issues.

L114: `transferFrom` can also fail due lack of approval for the amount of tokens requested for transfer. Use a message like `The `transferFrom` function must not fail.`
L318: `Give a ruling for a dispute. Must be called by the arbitrator.` This summary could confuse a reader with the ruling given to a round. I suggest we change it to something like: `Called by the arbitrator to enforce the final ruling.`
