### ISSUE TITLE
Security Review and Bug Bounties for Kleros ETH Escrow

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#202]
This is a bug bounty for [Escrow contract](https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol).

All contracts this contract rely upon are also part of the security review.

Vulnerabilities found can be paid up to 10 ETH for the most critical ones.
Bounties have already been posted on solidified.
Only the first reporter can be paid the bounty.

Even if no vulnerabilities are found, reports are still part of the general bounty program.
This issue can be completed by multiple contributors.

**Comment by n1c01a5** [comment]
The link to solidified is https://web.solidified.io/contract/5c2d58f8879c0e00179c6938
