### ISSUE TITLE
Make a contract for the cryptokitty dispute

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#22]
https://medium.com/kleros/announcing-who-gets-the-cryptokitty-infographic-contest-a52493a8d7dc

Party A and B create a “marriage smart contract”

They put the Cryptokitty in the Marriage Contract

Party A and B eventually split up. :(

A Dispute for the Cryptokitty is submitted by B, in which Kleros’ jurors can decide to :

    - Give the kitty to A
    - Give the kitty to B
    - Grant shared custody. The kitty will not be transferable without the agreement of both parties. Each party can use the kitty every other week.

**Comment by OssieTheCS** [comment]
"Each party can use the kitty every other week."

Does this mean that they can transfer the kitty in that week without the consent of the other?
Or what does "can use" exactly imply?

**Comment by mtsalenc** [comment]
Transfering or selling the kitty should require consent from both parties.
Use would mean: Placing and removing it from a siring auction, giving birth, breeding etc. Anything that won't make the other party loose control over it.
