### ISSUE TITLE
[Chore] Split this repo

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#231]
This repo is too big and creates compilation stack size issue. We need to split it into multiple ones.

**Comment by marsrobertson** [comment]
Just checking...

Is https://github.com/kleros/erc-792 part of this issue? cc @ferittuncer

**Comment by marsrobertson** [comment]
https://github.com/kleros/kleros-interaction/issues/248#issuecomment-482871592 - faster tests, better experience, higher productivity.

**Comment by ferittuncer** [comment]
> Just checking...
> 
> Is https://github.com/kleros/erc-792 part of this issue? cc @ferittuncer

Yeah.

**Comment by ferittuncer** [comment]
https://github.com/kleros/erc-792
https://github.com/kleros/ethereum-libraries
https://github.com/kleros/ethereum-rng
