### ISSUE TITLE
RealitioArbitratorProxy.computeWinner should add a grace period of 15s to commitment timeout

### ISSUE THREAD

**Issue by pacamara** [kleros/kleros-interaction#246]
`RealitioArbitratorProxy.computeWinner` protects non-timed-out commitments with:
```
require(revealTS <= uint32(now), 
    "Arbitration cannot be done until the last answerer has had time to reveal its commitment.");
```
A malicious miner can increase the block time by up to 15s and still get it accepted. For an unrevealed commitment which is in the last 15s of its commitment timeout, and if the miner requested arbitration, `computeWinner` deems the miner the winner. 

Therefore the `require(...)` should include a 15s grace period to guarantee the commitment is never timed out prematurely.

See https://github.com/pacamara/realitio-contracts/pull/1 for demonstration code.

(Issue identified from code review for bounty kleros/kleros-interaction#244 )

**Comment by clesaege** [comment]
This would complicate the code compared to just giving 15 more seconds of timeout.
