### ISSUE TITLE
How to run tests? ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#248]
```
truffle test test/arbitrable-token-list.js

Compiling your contracts...
===========================
Error: CompileError: ParsedContract.sol:207:47: ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.
    function balanceOf(address _owner) public constant returns (uint256 balance) {
                                              ^------^

Compilation failed. See above.
    at async.whilst.error (/Users/mars/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:375:1)
    at /Users/mars/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:969:1
    at next (/Users/mars/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:5222:1)
    at Promise.all.then.results (/Users/mars/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:357:1)
Truffle v5.0.12 (core: 5.0.12)
Node v11.6.0
```

```
truffle version
Truffle v5.0.12 (core: 5.0.12)
Solidity v0.5.0 (solc-js)
Node v11.6.0
Web3.js v1.0.0-beta.37
```

1. Shall I change the code in all the files?

2. Shall I change my Truffle / Solidity version?

3. Shall I change `pragma` on top of the files?

4. Shall I change a compiler setting so that an "error" is just a "warning"?

5. ... _(insert your suggestion here)_

**Comment by epiqueras** [comment]
Use the locally installed truffle version through the package.json scripts.

**Comment by marsrobertson** [comment]
Thanks for speedy reply, it work.

The only trouble:

```
time npm run test

real	2m53.071s
user	1m57.180s
sys	0m24.373s
```

I think if I specify which file it will run much faster...

**Comment by marsrobertson** [comment]
From `package.json`:

```
  "scripts": {
    "test:ganache": "ganache-cli --gasLimit 8000000 --quiet &",
    "test:truffle": "truffle test",
    "test": "run-p test:*",
  }
```

[`run-p`](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md):
> run given npm-scripts in parallel

So my understanding is that `test:*` will run in parallel `test:ganache` and `test:truffle`

When I run `npm run test` it works fine, although takes a few minutes to complete.

When I run these commands manually:
1. `ganache-cli --gasLimit 8000000`
2. `truffle test`

I'm getting the error, as I have a newer Solidity compiler.

> Use the locally installed truffle version through the package.json scripts.

How does `package.json` know which... Boom: https://stackoverflow.com/questions/44420381/how-does-npm-scripts-prioritise-local-dependency-over-global-ones

I've figured out myself, now I understand it better, useful `node.js` trick!

**Comment by marsrobertson** [comment]
```
  "scripts": {
    "arbitrable-test": "truffle test test/arbitrable-token-list.js",
    "simplified": "run-p test:ganache arbitrable-test"
  }
```

# Some time improvement

```
time npm run simplified
real	0m43.119s
user	0m43.100s
sys	0m3.295s
```

@epiqueras - it seems like compiling all the Solidity files still takes fair amount of time. Seems like Truffle is compiling all the assets, even though the test refers only to a very few of `.sol` Good developer experience = better adoption 🔥🔥🔥

**Comment by epiqueras** [comment]
Yeah that’s how truffle tests work.

**Comment by marsrobertson** [comment]
Maybe there is a better way. To compile only a few required `.sol` files to run the specific tests - better developer experience, less time waiting to compile...

Asked in their gitter channel: https://gitter.im/ConsenSys/truffle?at=5cb24f22b34ccd69e7b31e2a

**Comment by marsrobertson** [comment]
Here is my way of saving time: https://github.com/kleros/kleros-interaction/compare/master...marsrobertson:arbitrable-token-list

Putting only the required files in the `contracts` folder:

```
AppealableArbitrator.sol
Arbitrable.sol
ArbitrableTokenList.sol
Arbitrator.sol
CappedMath.sol
CentralizedArbitrator.sol
EnhancedAppealableArbitrator.sol
IArbitrable.sol
Migrations.sol
PermissionInterface.sol
```

```
real	0m27.281s
user	0m23.093s
sys	0m2.279s
```
