### ISSUE TITLE
Introduce _onlyArbitrator modifier for increased code readability.

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#251]
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/permission/ArbitrableAddressList.sol#L472-L490

The method is `public`

Later on in the body there is check: `require(request.arbitrator == msg.sender);`

I believe that for readability, it is a good candidate for `_onlyArbitrator` modifier.

Makes code easier to read, immediately you can tell.

**Comment by clesaege** [comment]
I'm not a fan of modifiers except the most basic ones. Here it would complexify the code.
