### ISSUE TITLE
requestStatusChange to be split into `addAddress` and `removeAddress`

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#252]
Looking at the method name `requestStatusChange` it is not instantly obvious that it is used for adding addresses to the list.

Use instantly obvious methods names:
- `addAddress` 
- `removeAddress`

Then they would call the same internal method with true / false parameter.

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/permission/ArbitrableAddressList.sol#L204

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/permission/ArbitrableAddressList.sol#L216-L221

**Comment by clesaege** [comment]
This already works is way and is deploy.
If you think it's not obvious, you can write comments.

**Comment by ferittuncer** [comment]
Another problem with it, we were exceeding block gas limit during development so we had to shrink the source code with some readability compromises. @marsrobertson
