### ISSUE TITLE
When initialising a DisputeSctruct avoid using ambiguous values such as 0 (refuse to arbitrate)

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#254]
Here: https://github.com/kleros/kleros-interaction/blob/50db202eee706f2832f99298b8d7f73fbffa3538/contracts/standard/arbitration/CentralizedArbitrator.sol#L71-L81

`ruling: 0` is a valid ruling (refuse to arbitrate)

Initialise it to `MAX_UINT` instead

Unless storing `0` has some gas saving implications. I still prefer clarity, readability, simplicity.

**Comment by clesaege** [comment]
Storing 0 is cheaper.

**Comment by marsrobertson** [comment]
Yes and no. I agree to a degree.

At some point in the future, in most of the cases _(unless really 0, “refuse to arbitrate”)_ someone else will have to pay the cost of storing one integer.

**As always, I opt for simplicity and adoption.**

If we are so much into gas savings, read this: https://medium.com/@novablitz/storing-structs-is-costing-you-gas-774da988895e

> Then, we changed creationTime from a uint64 to a uint48. This lets the top five fields all pack together into 32 bytes. Timestamps don’t need to be more than uint48, and Solidity (unlike most other languages) allows a uint to be any multiple of 8, not just 8/16/32/64 etc. (if you’re reeeally crunched for space, you can use a uint32 for timestamp — you’ll likely be dead before it causes a problem in 2106).

https://github.com/kleros/kleros-interaction/blob/50db202eee706f2832f99298b8d7f73fbffa3538/contracts/standard/arbitration/CentralizedArbitrator.sol#L22-L28

*(use proper types and align fields)*

**Comment by ferittuncer** [comment]
Well, yeah, we could use smaller types.
