### ISSUE TITLE
DRY (don't repeat yourself) when writing tests

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#255]
https://github.com/kleros/kleros-interaction/blob/master/test/multiple-arbitrable-transaction.js

Repeated 26 times:

`const lastTransaction = await getLastTransaction`

This surely can be extracted as an individual function?

Or use `beforeEach` block?

**Comment by clesaege** [comment]
Redundancy and repeating in tests is fine.
Tests should be the less abstact possible.

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/56893100-73ecda00-6a79-11e9-9017-8164fa1ea996.png)

The code is repeated so many times.

1. Is each of the functions exactly the same?

2. It's more lines, more things to analyze.

**Comment by clesaege** [comment]
Yeah, it makes it harder to miss something when writing it. You don't need to analyse tests, if you want more security you can make other ones as tests handles redundancy well.
