### ISSUE TITLE
Redefinition of MetaEvidence and other events

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#257]
Part of #243 (bounty)

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L51-L55

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L14

https://github.com/kleros/kleros-interaction/blob/96b34176090e3a17d5208f3093ec15a4482d7c43/contracts/standard/arbitration/IArbitrable.sol#L20-L24

**Comment by clesaege** [comment]
What do we need to redefine.

**Comment by marsrobertson** [comment]
I think quite the opposite.

I think there is a duplication.

Event is defined twice. 

Both in the `IArbitrable.sol` and the re-redefined in `MultipleArbitrableTransaction.sol`

Events are inherited: https://ethereum.stackexchange.com/questions/34666/are-events-not-inherited-in-solidity

**Comment by ferittuncer** [comment]
Yeah, it is forgotten.
