### ISSUE TITLE
Consistently emit Payment events

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#259]
https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L152

https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L167

Here there is no Payment event:
https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L181

**Comment by ferittuncer** [comment]
https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L57

**Comment by marsrobertson** [comment]
HMMM... Executing a transaction does not emit any events.

**Comment by ferittuncer** [comment]
I agree that event name is a bit misleading. But the intention is to use it for `pay` and `reimburse` functions.
