### ISSUE TITLE
Does it really matter if arbitration fee is paid directly by sender or receiver?

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-interaction#260]
https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L218

https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L244

Asking because in another project (Tokens on Trial, Curated Token Registry) there is a fee crowdfunding and anyone can fund that.

Whether or not this is game theory rational incentivization can be discussed on the forum: https://forum.kleros.io/t/proposal-kleros-cooperative-coommunity-fund-kccf-dao-and-funding-the-appeals/179

**Comment by marsrobertson** [comment]
Same applies with submitting evidence:

https://github.com/kleros/kleros-interaction/blob/bb41ba332cd88287ccc92072396eff0263b06dd7/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L292-L295

Jurors can do some research and present valuable findings.

**Comment by n1c01a5** [comment]
It matters to avoid a grieving attack. Indeed, otherwise anyone could disrupt the transaction between the parties by paying a relatively small amount (fee arbitration cost).

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/57567784-60753380-73d6-11e9-81ed-e48bb49bf4a9.png)

https://ethereum.stackexchange.com/questions/62829/what-does-griefing-mean

Can you explain in more details?

> paying a relatively small amount

How does it distrupt the transaction flow?

**Comment by n1c01a5** [comment]
Someone can pay the arbitration fee just to delay the transaction.

Le sam. 11 mai 2019 à 12:21, Mars Robertson <notifications@github.com> a
écrit :

**Comment by marsrobertson** [comment]
Thank you for providing real-life example.

Now I understand what does it mean (copy paste from StackOverflow):

> Such an attack doesn't benefit the attacker, but does make using the system more difficult for the victim
