### ISSUE TITLE
Implement AppealableArbitrator.sol

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#3]
This is a centralized arbitrator who can be appealed to another arbitrator.
The other arbitrator can be any kind of arbitrator.
This contract can inherit from CentralizedArbitrator.

**Comment by bitonator** [comment]
sent you a pull request on this

**Comment by clesaege** [comment]
PR: https://github.com/kleros/kleros-interaction/pull/18/files

**Comment by clesaege** [comment]
Few comments about how to implement it (but if you have something else which would work that's fine too):
-The Appealable contract must designate another Arbitrator contract for appeals.
-You can get the cost of appeal by asking the other Arbitrator contract.
-After a ruling is made, you need to let some time for parties to appeal, otherwise if you call directly the arbitrable contract, the ruling will be enforced without possibility of appeal.

**Comment by bitonator** [comment]
Got it, will look into this

**Comment by bitonator** [comment]
For assigning the Arbitrator contract, I could add an `assignDispute` method and call it from `appealSuccessful`, but I'm wondering whether I should add it to `AppealableArbitrator` or `Arbitrator`. 

Regarding the ruling, I'll move the `rule` method inside the else clause and add a `appealTimeout` method which will execute the ruling

**Comment by clesaege** [comment]
AppealableArbitrator, after an appeal is made, need to transfer the dispute to the appeal arbitrator, so it is in AppealableArbitrator. So AppealableArbitrator must also be Arbitrable.

**Comment by ferittuncer** [comment]
Looks like @bitonator gave up. I am starting work on this.

**Comment by clesaege** [comment]
You may want to look at https://github.com/kleros/kleros-interaction/issues/4 as they are quite similar.
