### ISSUE TITLE
Disable Evidence Submission After Draw Period

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-interaction#31]
Evidence should only be submittable before the creation of the dispute, and during the "Activation" and "Draw" periods.

Otherwise jurors can have incomplete or different information when voting and this would mess up the Schelling Point.

**Comment by clesaege** [comment]
Yeah, we should have a way to guarantee that no more evidence can be submitted after the jurors can vote.
This would need to go into the bigger scope of an evidence standard.

**Comment by clesaege** [comment]
Well, it seems that the interface should just not display evidence submitted late.

**Comment by epiqueras** [comment]
@satello Is this simple to implement in the API?

**Comment by satello** [comment]
Yes relatively. It might be better to leave it up to the interface to decide if they want to display the evidence or not though. Or make it configurable in the api instead of just shadow blocking late evidence. We don't know what use cases people will use `kleros-api` for.

**Comment by epiqueras** [comment]
Making it optional and tagging it for the UI makes sense.
