### ISSUE TITLE
Make a general arbitrable deposit contract

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#38]
Make

 a contract where:
- The owner can add a deposit on the contract.
- Any party may make a claim of value X against the contract creator by also putting a deposit D=X*r, where r is the proportion of the claim that the claimant has to deposit.
- In case of a claim, the owner can propose to accept the claim up to a certain amount A (note that we may have A==0), if it is the full amount (A==D), he claim is settled, and ETH from the owner deposit are given to the claimant.
- Otherwise, a dispute resolution process ensues.
- If the Arbitrator rules for the claimant ETH from the owner deposit are given to the claimant.
- If the Arbitrator rules for the owner, the deposit D of the claimant is added to the deposit of the owner, then, A is taken from the deposit of the owner to be given to the claimant.

**Comment by l-hartman** [comment]
I think my [PR](https://github.com/kleros/kleros-interaction/pull/39) is sufficient. If not, please let me know what needs to be fixed.
Thanks!

**Comment by clesaege** [comment]
Thanks for you contribution, I added comments on it.

**Comment by ferittuncer** [comment]
Should this be closed?

**Comment by clesaege** [comment]
Yes :)
