### ISSUE TITLE
Submit a ERC for the permission standard

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#9]

**Comment by clesaege** [comment]
Permission standard instead:

**Comment by clesaege** [comment]
EIP: XXX
Title: Permission Standard
Status: Draft
Type: Informational
Category: ERC
Author: Clément Lesaege <clement@kleros.io>
Created: 2018-02-03

Abstract
--------------

This standard specifies that the standard naming of a public function indicating that an element is allowed is `isAllowed`.

Motivation
--------------

Some contracts require calling others in order to know if an element is allowed. A contract can need to know if an address has the right to interact with it or if an item belongs to the list of allowed items (ex: curated list).
This standard is straightforward but required for interoperability.

Specification
--------------

### isAllowed

This function returns `true` if the element is allowed, `false` otherwise.
Specific types can be used instead of`bytes32` as long as they are not longer than 32 bytes.
``` is
function isAllowed(bytes32 _element) returns(bool allowed)
```

Rationale
--------------
- Contracts and interfaces sometimes need to know if some particular element is allowed or not.
- The standard allows the abstraction of the permission brick of a dapp. It allows parties to choose a contract with arbitrary complex rules to determine if an element is allowed or not.
- Allowing types others than bytes32 provides better typing, thus better readability, to contracts without breaking interoperability.

Implementations
--------------
- https://github.com/kleros/kleros-interaction/tree/master/contracts/standard/whitelist
- https://github.com/clesaege/blacklist

**Comment by decanus** [comment]
@clesaege I feel ``isPermitted`` would be better terminology in this situation rather than ``isAllowed``

**Comment by clesaege** [comment]
@decanus I edited it with isPermitted.

**Comment by decanus** [comment]
@cleaage should the standard also allow for multiple arguments?

**Comment by decanus** [comment]
Maybe we should define that the function can be extended if multiple arguments are required. Making the 32bytes version only a subset of the larger isPermitted standard

**Comment by clesaege** [comment]
In this case, we would have 2 isPermitted functions in the standard. The one with `bytes` would work with the one with `bytes32` but not reciprocally.
So with 2 abstract classes
Permitting
LargePermitting
?

**Comment by decanus** [comment]
I wouldn’t do one with bytes. I would indicate that bytes32 is not a limitation of what can be used. Someone may want to use an address and sting together for example

**Comment by clesaege** [comment]
But then it's not interoperable as contract just having bytes32 would not be able to interact correctly with those with bytes.

**Comment by decanus** [comment]
Ok let's leave it at bytes32 for now then

**Comment by clesaege** [comment]
Everything OK? Can we publish?

**Comment by decanus** [comment]
@clesaege I am fine with it yes

**Comment by clesaege** [comment]
Done: https://github.com/ethereum/EIPs/issues/892
